language: r
cache: packages
env:
  global:
  - secure: UIbgMWqRrygTCOcmkZ34vAmrYCIJYtFSCiR09XO0wuPIvipEi9c0gdjn6zGRdjnNg7S7B4F7bT4BpF1/VwXistzX4qf7tAamImeTpUdrv7FHGYWCvi1PlKDxhopTSmU9Y4o7jH8AoR9ZI+Bitc33JQOnDpyo50jeb7TXNmUz4IBpvijhxHPvoEitzQ+Pb+minW+H/TrKE1dU0w6mTh5xc4+EjQoU77+RfaIQlEpSEOuYpT3DjrsiJ97XXTLOKfn+Ye3wLHondkMGkVso6OnM4J6N55WhPQpMuYzzmk+L33DixL36E1xPzsEizSOR8NsPuKTPjvq/gT0U17AleCYNl/raP9ROpXGKdFzXc9lVZcAtvtpIGA5aqmHrVIs8MgcmdwPiL0qx3zHiSyRGBepPcMlvwzmNlAeYXqL3tkGCMdQp63Vvy20BliAI8Uhd+1VNha3A0SXmTrWHQt79r76INuJV8/x3S9uygnoiYWLfqoQrWkOOrAxib5IKrSwwS5cmhKsKII62l0tQEPaWdIFsdFxnJsbyDQLqdJjs7BTO1HTcgXF/SNCCnto+IoTVxhYriV6IEHcTXfausNzerYC+SWgs5ejasnHcoln4/xWR7kNYe1Xg22hycmbeL1zYjvX98Xtv9jqh+pdcIFdxvOaH9svhIS+oVbL9zRXpXha3h90=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
